[package]
name = "supervised-binary-insertion-sort"
version = "0.1.0"
authors = ["girkovarpa@protonmail.com <GirkovArpa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
